
# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="yyyy-mm-dd"

# Customizations
source $HOME/.shell-functions
source $HOME/.shell-aliases
source $HOME/.shell-env
if [[ -f $HOME/.shell-machine-specific ]]; then
  source $HOME/.shell-machine-specific
fi


####################
# User configuration
####################

# History settings
HISTSIZE=1000
SAVEHIST=2000
setopt appendhistory

# don't beep
unsetopt beep
